### ISSUE TITLE
program crashed

### ISSUE THREAD

**Issue by albertnanda** [goccy/go-json#142] opened 2021-02-19 18:23 UTC
Here is my code:
Go version 1.16
```
package main

import (
	"os"

	"github.com/goccy/go-json"
)

func main() {
	file, _ := os.Open("file")
	defer file.Close()
	decoder := json.NewDecoder(file)
	data := map[string]interface{}{}
	for i := 0; i < 1000; i++ {
		decoder.Decode(&data)
		//fmt.Println(data)
	}

}
```
It works fine till 900 sentences, but crashes at 1000 with the following message:
```
(base) ~/gocode/test$ ./json_go 
panic: runtime error: slice bounds out of range [28:26]
goroutine 1 [running]:
github.com/goccy/go-json.decodeEscapeString(0xc000518000, 0x0, 0x0)
/pkg/mod/github.com/goccy/go-json@v0.4.6/decode_string.go:136 +0xfa5

```

**Comment by goccy** [comment] 2021-02-20 06:05
Thank you for your report.
Can you give me some reproducible data for debugging ?
Also, does this problem reappear in the master branch ?

**Comment by albertnanda** [comment] 2021-02-28 06:58
@goccy I am unable to share the real data, the dummy data doesn't induce a crash. I will try to reproduce the same and let  you know. However, here is something that might pique your interest. This is a comparison of python vs go json decoding performance..
To generate the json please run the following code:
```
import pandas as pd
d = [{'sentences': ['Sent', 'Sent1', 'Sent2'], 'content_id': 'String', 'id': 'String', 'date': '2000-03-28', 'label': '1', 'categories': ['String']}]
d = d*200000
df = pd.DataFrame(d)
df.to_json("./dummy.json",orient='records',lines=True)
``` 
Now, here is a comparison between python, go(encoding json), go(goccy)
Code:
```
import json
with open("./dummy.json") as f:
    for index,line in enumerate(f):
        if index==100000:
            break
        json.loads(line)
```
```
package main

import (
	"os"

	"github.com/goccy/go-json"
)

func main() {
	file, _ := os.Open("./dummy.json")
	defer file.Close()
	data := map[string]interface{}{}
	decoder := json.NewDecoder(file)
	for i := 0; i < 100000; i++ {
		decoder.Decode(&data)
	}
}
```
```
package main

import (
	"encoding/json"
	"os"
)

func main() {
	file, _ := os.Open("./dummy.json")
	defer file.Close()
	data := map[string]interface{}{}
	decoder := json.NewDecoder(file)
	for i := 0; i < 100000; i++ {
		decoder.Decode(&data)
	}
}
```
Results:
Python:
```

real    0m0.425s
user    0m0.266s
sys     0m0.094s
```
Go(encoding/json)
```
real    0m0.591s
user    0m0.438s
sys     0m0.250s
```
Go(goccy)
```

real    0m0.881s
user    0m0.391s
sys     0m0.203s
```

**Comment by goccy** [comment] 2021-03-20 11:58
This issue title is `program crashed` but couldn't reproduce it .
So I closed this issue. If you want to report performance issue, please let me know by the another issue .

**Closed by goccy** 2021-03-20 11:58 UTC
