### ISSUE TITLE
Panic with Go 1.18beta1

### ISSUE THREAD

**Issue by iredmail** [goccy/go-json#308] opened 2021-12-25 05:32 UTC
Sample code to reproduce the panic. Note: same code works fine with the builtin `encoding/json`.

```
package main

import (
	"github.com/goccy/go-json"
	// "encoding/json"
)

func main() {
	m := map[string]bool{
		"success": true,
	}

	_, _ = json.Marshal(m)
}
```

**Comment by orisano** [comment] 2021-12-25 06:04
It is probably due to this commit.
https://github.com/golang/go/commit/1b2d794ca3ba60c2dbc958a271662784a7122739

**Comment by goccy** [comment] 2021-12-27 09:20
Thank you for the reporting and suggestions for the cause .
This bugs was probably fixed with https://github.com/goccy/go-json/pull/310 .

**Closed by goccy** 2021-12-27 09:20 UTC

**Comment by iredmail** [comment] 2021-12-27 11:08
Dear @goccy 

Any plan for tagging a new release with this fix?
